### ISSUE TITLE
Players return to server three to four meters lower than they were when they left

### ISSUE THREAD

**Issue by gdludus** [CardboardPowered/cardboard#233]
This is a really weird bug.

I have FabricMC 1.17.1 with loader 0.11.6 running on a Pebblehost server which functions just fine on its own. The second I add the Cardboard mod, however, I get a bug where players who were previously in the server will return to the server in a spot three or four blocks lower than where they were when they left. The only plugin I have installed through the Cardboard mod is called discord whitelister, and it does exactly what it sounds like it does. It taps into a channel in a discord server I own and lets users whitelist themselves. This bug occurs regardless of that plugin's presence. I have no other Fabric mods installed.

Here's the pastebin for what the console spits out on startup:
https://pastebin.com/kT0Aw3mb

Please help.

Thanks,
Ludus

**Comment by gcaddyo** [comment]
I also encountered the same problem on 1.17.1

**Comment by gdludus** [comment]
The current workaround is to use two plugins called JoinCommands and Essentials. JoinCommands is usually used to send a message to the player when they join but I've instead used `/sudo {PLAYER} home bed` to get them to teleport to their bed, which in my SMP is the only home they have access to. A less consistent but more continuous workaround would be to use `/tp {PLAYER} ~ ~4 ~` as that will keep them back at the location they left from; however, I don't think the tildes would work since the player isn't the one running the command. Maybe try sudoing the command on the player (since you can have multiple commands, you can make one to add essentials.tp.position to the player and then take it away after the command is run).

**Comment by gdludus** [comment]
> Have not encountered with login / logout, but with entering different worlds (Nether, End) through their respectable vanilla portals. Big problem as End and nether portals have the chance to spawn over the Void / lava!

I guess the best workaround for this is to use a plugin like Multiverse-Core to switch worlds, but then nobody can have their own portal.

**Comment by BEMZ01** [comment]
> The current workaround is to use two plugins called JoinCommands and Essentials. JoinCommands is usually used to send a message to the player when they join but I've instead used `/sudo {PLAYER} home bed` to get them to teleport to their bed, which in my SMP is the only home they have access to. A less consistent but more continuous workaround would be to use `/tp {PLAYER} ~ ~4 ~` as that will keep them back at the location they left from; however, I don't think the tildes would work since the player isn't the one running the command. Maybe try sudoing the command on the player (since you can have multiple commands, you can make one to add essentials.tp.position to the player and then take it away after the command is run).

The problem is here though that the TP height is random. So if I implemented the work arounds, the player would sometimes get tped above the portal.

**Comment by gdludus** [comment]
The bug was fixed with 1.17 #26, and now the problem doesn't happen between worlds nor when relogging. Happy Cardboarding!

**Comment by gdludus** [comment]
Nope. The problem is back and worse than before. Now players can be teleported up to 13 blocks below the portals between worlds and when relogging. This needs a fix. Asap.

**Comment by gdludus** [comment]
Nope. The problem is back and worse than before. Now players can be teleported up to 13 blocks below the portals between worlds and when relogging. This needs a fix. Asap.

**Comment by BEMZ01** [comment]
Can agree, players within my server are now being teleported into bedrock and blocks along with the void.

**Comment by gdludus** [comment]
Current fix, since it's a random amount of blocks, is to use JoinCommands and WorldEdit to, on join, OP the player, sudo them to use //ascend to get them back to where they were, and then deOP them again. For interdimensional travel, I'm just using public warps, which sucks, but it's the only consistent solution I've found.

**Comment by IsaiahPatton** [comment]
Should be fixed now in latest update.

**Comment by cyhhao** [comment]
1.17-#40 still have this bug

occurs once in 3 times on average
