### ISSUE TITLE
DiscordSRV plug-in only communicates one way on Fabric 1.17.1 server

### ISSUE THREAD

**Issue by Killakilla2** [CardboardPowered/cardboard#256]
While using the plug-in DiscordSRV-Build-1.23.0.jar which I have verified is setup correctly wirh apex hosting staff the plug-in does not communicate two ways with discord.  Chats are abele to be sent from discord to in game but not from in game to discord.  The plug-in developers stated this is a know issue with cardboard and communication with apps.  Please assist

**Comment by IsaiahPatton** [comment]
Should be fixed now.

**Comment by wrecktify** [comment]
I am still having this issue with the latest version of Fabric, Cardboard & Discordsrv.
